### ISSUE TITLE
demo link is broken

### ISSUE THREAD

**Issue by babatundebusari** [microcmsio/react-hooks-use-modal#20]
Demo

https://shibe97.github.io/react-hooks-use-modal/

![image](https://user-images.githubusercontent.com/6054104/129473963-951b6493-ff96-428f-a2a3-ac7d15f07d92.png)

**Comment by shibe97** [comment]
Sorry, I fixed.
Correct link is here.
https://microcmsio.github.io/react-hooks-use-modal/
