### ISSUE TITLE
Not supporting in react@18.0.0

### ISSUE THREAD

**Issue by kato83** [microcmsio/react-hooks-use-modal#64]
こんにちは、現状 React 18 では使用できないようになっていそうですが、使用できるような調整は可能でしょうか？

https://github.com/microcmsio/react-hooks-use-modal/blob/610974ad9c47049039421519b252f66beedb7181/package.json#L45-L48

また、なにか手伝えることはありますか（React 18だと動かなさそうな箇所の目星はありますか）？

この modal の hook はとても使いやすいので React 18 でも引き続き使用できたらと考えています。

**Comment by dc7290** [comment]
ver3.2.0で対応👏

**Comment by kato83** [comment]
@dc7290 マージ及びnpm publish対応ありがとうございました！
